### PR TITLE
BUG: click.prompt cannot handle dates

### PR DESCRIPTION
**Pull request by pastewka**

### CODE REVIEW

**Comment by tjelvar-olsson** [comment]
@pastewka I edited your fix slightly to change the output format from '2020-03-04 00:00:00' to '2020-03-04' (commit dcea0f3db0a2ede3471e857689e7f8d38dadb9fa)

I also added your contribution to the change log (commit f635bb87367b222b518502795f59c20ab5fe2cec) and the contributors file (commit 71185646f7da5967c159fc3464e545ffdae5a96a)

This code has been included in the 0.23.1 release of dtool-create: https://pypi.org/project/dtool-create/0.23.1/

**Comment by tjelvar-olsson** [comment]
Note that my edit in (commit dcea0f3db0a2ede3471e857689e7f8d38dadb9fa) converts Yaml dates to strings:

I.e. if the template is:

```
---
sometime: 2020-03-04
```

and a user updates the date using ``dtool readme interactive`` to 2020-02-01 the resulting README.yml file will be:

```
somtime: '2020-02-01'
```

(note the quotes around ``'2020-02-01'``).

I did not realise that isoformat dates without quotes were a special type in YAML.

I can change the code to return ``2020-02-01`` without quotes if that is desirable. I.e. for the yaml to conserve the date type from the template to the resulting dataset readme.

What do you think?

**Comment by pastewka** [comment]
It may be better to have this explicitly as a date, but I am not sure how relevant this is. If you convert back, than there is probably no way to get rid of the time information (00:00:00 above)? In that case I would opt for simplicity.

Dates and times are weird anyway since you really also need the time zone to interpret them properly, unless there is some agreement to normalize to UTC. I guess this would be important in the context of data provenance.

**Comment by tjelvar-olsson** [comment]
I think I can get it to return the date without the time information (00:00:00) by changing the line:

```
d[key] = new_value.date().isoformat()
```

to:

```
d[key] = new_value.date()
```

**Pull request merged**
